# Generated by Django 5.0.3 on 2024-03-13 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Absentees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("roll_no", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AdministrationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("class_coordinator", models.CharField(max_length=255)),
                ("class_representative", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CourseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("semester", models.IntegerField()),
                ("department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=255)),
                ("total_classes", models.IntegerField()),
                ("faculty_name", models.CharField(max_length=255)),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FacultyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FeeDefaulters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                ("batch", models.CharField(max_length=255)),
                ("roll_no", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("type_of_user", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=255)),
                (
                    "ct_1",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "ct_2",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "assignments",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "end_sem",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("grade", models.CharField(max_length=255)),
                ("roll_no", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "roll_no",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("joining_year", models.CharField(max_length=255)),
                ("blood_group", models.CharField(max_length=255)),
                ("semester", models.IntegerField()),
                ("contact_number", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("gender", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=255)),
                ("task", models.CharField(max_length=255)),
            ],
        ),
    ]
