# Generated by Django 5.0.3 on 2024-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_absentees_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absentees",
            name="time_slot",
            field=models.CharField(max_length=255),
        ),
    ]
