# Generated by Django 5.0.3 on 2024-03-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_absentees_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentcourses",
            name="department",
            field=models.CharField(default="none", max_length=255),
        ),
    ]
