# Generated by Django 5.0.3 on 2024-03-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Todolist",
        ),
    ]
