# Generated by Django 5.0.3 on 2024-03-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_rename_todo_todolist"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
