# Generated by Django 4.0.6 on 2024-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_timetable_weeklytimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('message_type', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='administrationinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='administrationinfo',
            name='staff_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='administrationinfo',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='administrationinfo',
            name='position',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
