# Generated by Django 4.0.6 on 2024-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_facultytimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(default=None),
        ),
    ]
