# Generated by Django 4.0.6 on 2024-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_timetable_joining_yr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(),
        ),
    ]
