# Generated by Django 4.0.6 on 2024-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_timetable_joining_yr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_1',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_2',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_3',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_4',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_5',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_6',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_7',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
