# Generated by Django 4.0.6 on 2024-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_timetable_day_alter_timetable_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_4',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_5',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_6',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slot_7',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
