# Generated by Django 4.0.6 on 2024-04-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_timetable_day_alter_timetable_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='joining_yr',
        ),
    ]
