# Generated by Django 4.0.6 on 2024-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_timetable_day_alter_timetable_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
