# Generated by Django 4.0.6 on 2024-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_timetable_joining_yr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='joining_yr',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
