# Generated by Django 4.0.6 on 2024-04-15 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_timetable_joining_yr'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=250)),
                ('faculty', models.CharField(max_length=140)),
                ('internal_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('end_lab', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('roll_no', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=150)),
            ],
        ),
    ]
