# Generated by Django 4.0.6 on 2024-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_labresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='course_type',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
