# Generated by Django 4.0.6 on 2024-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_courselist_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
